config/routes.rb
Rails.application.routes.draw do
 
  post 'messages/copy'

  resources :messages
 
  root 'welcome#index'
end

app/models/device_token.rb
class DeviceToken < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :minutes, presence: true, length: { minimum: 1 }, numericality: { only_integer: true }
  validates :reason, presence: true, length: { minimum: 1 }
  validates :from, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/device_tokens_controller.rb
class DeviceTokensController < ApplicationController
end

app/controllers/messages_controller.rb
require "uri"
require "net/http"

class MessagesController < ApplicationController
  http_basic_authenticate_with name: "p", password: "6896", except: [:index, :show]

  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def edit
    @message = Message.find(params[:id])
  end

  def copy
    @message = Message.find(params[:format])
    puts @message
    @new_message = @message.dup
    send_msg(@new_message)
  end
 
  def create
    @message = Message.new(params.require(:message).permit(:minutes, :reason, :from))
    send_msg(@message)
  end


  def destroy
    @message = Message.find(params[:id])
    @message.destroy
 
    redirect_to messages_path
  end

  def send_msg(message)
    @token = "chXlfIB-EZA:APA91bHhyw9s7HFSZxSd2zn0y1UtLbqJotw-2CwBZaOhMpyzLAbCYgV0qs_pBCoPqfKbAXbjoExW7VKqcCpHpfbpZeKJbvpZ9BHHHrWw08tzwwZxg8fKN98ZDYbg64Uyg_jwtv0UuddQ"
      
    if message.save
      uri = URI.parse("https://fcm.googleapis.com/fcm/send")
      uri.query = URI.encode_www_form(
                       "data.minutes" => message.minutes,
                       "data.reason" => message.reason,
                       "data.from_who" => message.from,
                      "to" => @token)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      request = Net::HTTP::Post.new(uri.request_uri)
      request.add_field 'Authorization', 'key=AIzaSyDOKv0PXEdhswb8IzEl5JhFOqODHdFDG94'
      request.add_field 'Content-Type', 'application/x-www-form-urlencoded;charset=UTF-8'
      puts http.request(request).body
      
      redirect_to message
    else
      render 'new'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/device_tokens_helper.rb
module DeviceTokensHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Video Time Admin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/copy.html.erb
<h1>Messages#copy</h1>
<p>Find me in app/views/messages/copy.html.erb</p>

app/views/messages/index.html.erb
<h1>Listing messages</h1>
 
<%= link_to 'New message', new_message_path %>
<br>
<br>
<table>
  <tr>
    <th align="center">Minutes&nbsp;&nbsp;&nbsp;</th>
    <th align="center">&nbsp;&nbsp;&nbsp;Reason&nbsp;&nbsp;&nbsp;</th>
    <th align="center">&nbsp;&nbsp;&nbsp;From&nbsp;&nbsp;&nbsp;</th>
    <th colspan="3"></th>
    <th colspan="3"></th>
    <th colspan="3"></th>
  </tr>
 
  <% @messages.each do |message| %>
    <tr>
      <td align="left"><%= message.minutes %></td>
      <td align="center"><%= message.reason %></td>
      <td align="center"><%= message.from %></td>
      <td>&nbsp;&nbsp;&nbsp;</td>
      <td align="center"><%= link_to 'Show', message_path(message) %></td>
      <td align="center"><%= link_to 'Destroy', message_path(message),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <td align="center"><%= link_to '(  Copy  )', messages_copy_path(message.id),
              method: :copy,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/messages/new.html.erb
<%= form_for :message, url: messages_path do |f| %>  

  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@message.errors.count, "error") %> prohibited
        this message from being saved:
      </h2>
      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :minutes %><br>
    <%= f.text_field :minutes %>
  </p>
 
  <p>
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </p>
 
  <p>
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p>
  <strong>Minutes:</strong>
  <%= @message.minutes %>
</p>
 
<p>
  <strong>Reason:</strong>
  <%= @message.reason %>
</p>

<p>
  <strong>From:</strong>
  <%= @message.from %>
</p>

<%= link_to 'Back', messages_path %>

app/views/welcome/index.html.erb
<h1>Video Time Admin</h1>
<%= link_to 'Messages', controller: 'messages' %>